name: dartboot_core
description: The core library for DartBoot framework. https://github.com/luodongseu/dartboot.
version: 1.0.15
homepage: https://github.com/luodongseu/dartboot_core

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  dartboot_annotation: ^1.0.0
  dartboot_util: ^1.0.0
  dio: ^3.0.10
  uuid: ^2.2.2
  mutex: ^1.1.0
  source_gen: ^0.9.4+6
  analyzer: ^0.38.0
  build: ^1.2.2
  build_runner: ^1.9.0
  logging: ^0.11.4
  yaml: ^2.2.1
  stack_trace: ^1.9.6

dev_dependencies:
  test: any

